spring.application.name=configserver
server.port=8084
#eureka properties
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.server.git.uri=https://github.com/Rutuja-Patil-1535/application-config/



