spring.application.name=configserver
server.port=8084
#eureka properties
#eureka.client.service-url.defaultZone=http://servicereg:8761/eureka/
eureka.client.enabled=false
spring.cloud.config.server.git.uri=https://github.com/Rutuja-Patil-1535/application-config/



