spring.application.name=gateway

server.port=8085


#eureka properties
#.eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.endpoints.web.exposure.include=*
management.tracing.enabled=true

#gateway
#name of route
spring.cloud.gateway.routes[0].id=company_service
spring.cloud.gateway.routes[0].uri=lb://companyms
#list of conditions that the incoming request should match to the route if request matching the request is send forward
# **(wildcard) matches sequence of any characters & url name is same as in controller
spring.cloud.gateway.routes[0].predicates[0]=Path=/companies/**

spring.cloud.gateway.routes[1].id=job_service
spring.cloud.gateway.routes[1].uri=lb://jobms
spring.cloud.gateway.routes[1].predicates[0]=Path=/jobs/**

spring.cloud.gateway.routes[2].id=review_service
#spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].uri=lb://reviewms
spring.cloud.gateway.routes[2].predicates[0]=Path=/reviews/**

spring.cloud.gateway.routes[3].id=eureka_server
spring.cloud.gateway.routes[3].uri=http://localhost:8761
spring.cloud.gateway.routes[3].predicates[0]=Path=/eureka/main
#eureka ui is running on the http://localhost:8761/ but client sends /eureka/main so get correct ui of eureka
#we use setpath to convert eureka/main to / so the request becomes http://localhost:8761/ instead of http://localhost:8761eureka/main
spring.cloud.gateway.routes[3].filters[0]=SetPath=/

spring.cloud.gateway.routes[4].id=eureka_server_static
spring.cloud.gateway.routes[4].uri=http://localhost:8761
#with the help of this we get eureka all /eureka/css/**
#/eureka/js/**
#/eureka/images/**
spring.cloud.gateway.routes[4].predicates[0]=Path=/eureka/**


logging.level.root=info
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=info
logging.level.org.springframework.cloud.gateway=trace